### ISSUE TITLE
要不要一起来这里搞

### ISSUE THREAD

**Issue by mishengqiang** [yanyu0517/yarnpkgcn#1]
我看你也想做一个yarn中文网。
我看到@zhaotoday 也做了一个repo，并且有.cn域名，我们一起搞起来吧。

**Comment by xcatliu** [comment]
@zhaotoday @yanyu0517 @mishengqiang 
我看到官网支持多语言，所以想翻译好之后直接提 pr 就可以了，我已经提了一个 issue，大家一起来吧！

Issue: https://github.com/yarnpkg/website/issues/176
Forked repo: https://github.com/xcatliu/yarnpkg-website
Demo website: http://yarnpkg.xcatliu.com/zh-Hans/
